language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx
      
dist: trusty
addons:
    apt:
        sources:
            - kubuntu-backports
        packages:
            - cmake
            
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install curl xorg-dev libgl1-mesa-glx libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev mesa-common-dev libfreetype6-dev libpng12-dev libjpeg8-dev libtiff5-dev zlib1g-dev -y && sudo curl -o /usr/include/GL/glext.h https://www.khronos.org/registry/OpenGL/api/GL/glext.h && git clone https://github.com/glfw/glfw && mkdir buildglfw && cd buildglfw&& cmake ../glfw && make && sudo make install && cd ..; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install freetype libpng libjpeg libtiff zlib glfw -y || true; fi

script:
  - gcc -v && g++ -v && cmake --version
  - pwd && ls
  - mkdir build && cd build && cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release 
  - make all
  - ctest -v
  
branches:
  only:
  - master
  
notifications:
    email:
        recipients:
            - matusnov@gmail.com
    on_success: never
    on_failure: always