language: cpp
matrix:
  include:
  - compiler: gcc
    os: linux
    env:
    - ARCH=x86_64
    - TOOLSET=linux-gnu
  - compiler: clang
    os: osx
    env:
    - ARCH=x86_64
    - TOOLSET=apple-darwin
dist: trusty
addons:
  apt:
    sources:
    - kubuntu-backports
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-4.9
before_script:
- chmod +x .ci/gittag.sh
- chmod +x .ci/deps.sh
- "./.ci/deps.sh"
- "./.ci/gittag.sh"
script:
- chmod +x .ci/build.sh
- chmod +x .ci/package.sh
- chmod +x .ci/test.sh
- "./.ci/build.sh"
- "./.ci/test.sh"
- "./.ci/package.sh"
branches:
  only:
  - master
  - devel
notifications:
  email:
    recipients:
    - matusnov@gmail.com
  on_success: always
  on_failure: always

deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  name: "FineFramework - compiled - $TRAVIS_TAG"
  body: "Binary distribution of FineFramework DLLs for Visual Studio 2013, Visual Studio 2015, Visual Studio 2017, MinGW-w64, Linux, and OSX (both 32-bit and 64-bit)"
  draft: false
  file_glob: true
  api_key:
    secure: lUJnilARIKozAS5OKbvFPjYis21mUk6BSdTMLGdKf0T1F9hoV3Asb/qI8siF2c6/7KMq6xibt5TH3O27a7HuNuzgckPpyYiFoOcMzDQtShPJ8qCnJJtZK/Fjb8Z7pe4zYTjIY+NjvsPd1SGhqb3YR8oLSOqr6WVocp0js5QPJJakbX4PMV2Ir4yUWgC/A/6e53gvTfCBlxM6cKbcrX8spPaKbU7GdE0XpVgoLD/qPcteZJjWJSrLHT4hM5nTcKdbClQIdsN0LEz74zE0C5KmIWcyW/PoJpxqWMX6Zdk7105Zo0sbTKDTsyxGWHnfqcrfG8fAikGTYAzTU1zTv9fykJnS2fMhVcLBSMl2KtnN7HWCFCD43T8y5qqlreF1/KPdNypIQrwOC4ZkmcyiorLWCyU2vXKeAgGTaQyi+X3PSMlEsgbnZm0S+kIX5XxWuwW/5Qu3Wzq7LvEdXfK3u+fb7yoPEZ+di3ZioJt7zrxZqwEy1gcq3wV5WYa7gBQa05T6c35D/nHHipiIDXubhL+mP83b9SSO81ubOYBedSf3dht0u/B/Qn9Vta+gnquuP+/jvvPXzp4dZBcJfGfsjrGMkLA3VVf79POSYWoYwfS2DlFzZApxYBsP3rROWaPMN1jSYzqaur3diyOtq3Ad/Af5oso+bt8VcjpY7GlyYfCZa6g=
  file: ffw-*.zip
  on:
    tags: false
    repo: matusnovak/fineframework
    branch: master
