language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx
      
dist: trusty
addons:
    apt:
        sources:
            - kubuntu-backports
        packages:
            - cmake
      
install:
  - echo "Installing..."
  
script:
  - echo "Bulding..."
  - gcc -v && g++ -v && cmake --version
  - pwd && ls
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release 
  - make all
  - echo "     " | make test
  
branches:
  only:
  - master
  
notifications:
    email:
        recipients:
            - matusnov@gmail.com
    on_success: never
    on_failure: always