language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx
      
dist: trusty
addons:
    apt:
        sources:
            - kubuntu-backports
        packages:
            - cmake
      
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install xorg-dev libglu1-mesa-dev mesa-common-dev libfreetype6-dev libpng12-dev libjpeg8-dev libtiff5-dev zlib1g-dev -y; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install freetype libpng libjpeg libtiff zlib glfw -y || true; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then git clone https://github.com/glfw/glfw ./deps && mkdir ./deps/build && cd ./deps/build && cmake ../glfw && make && sudo make install; fi
  
script:
  - gcc -v && g++ -v && cmake --version
  - cd /home/travis/build/matusnovak/fineframework && pwd && ls
  - mkdir build && cd build && cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release 
  - make all
  - echo "     " | make test
  
branches:
  only:
  - master
  
notifications:
    email:
        recipients:
            - matusnov@gmail.com
    on_success: never
    on_failure: always