language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx
      
install:
  - echo "Installing..."
  
script:
  - echo "Bulding..."
  - pwd && ls
  - cd fineframework
  - mkdir build
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release 
  - make all
  - echo "     " | make test
  
branches:
  only:
  - master
  
notifications:
    email:
        recipients:
            - matusnov@gmail.com
    on_success: never
    on_failure: always