version: '{build}'

#---------------------------------#
#      general configuration      #
#---------------------------------#
branches:
  only:
    - master
    - devel
  except:
    - gh-pages
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
platform: Any CPU
init:
- cmd: >-
    echo "Compiling with: %GENERATOR%"
    echo "Using dependencies: %ARCH%-%TOOLSET%.zip"

#---------------------------------#
#    environment matrix           #
#---------------------------------#
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    TOOLSET: vc12
    ARCH: win32
    GENERATOR: '"Visual Studio 12 2013"'
    MAKE: MSBuild.exe
    CONFIGURATION: Debug
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: vc14
    ARCH: win32
    GENERATOR: '"Visual Studio 14 2015"'
    MAKE: MSBuild.exe
    CONFIGURATION: Debug

#---------------------------------#
#            steps                #
#---------------------------------#
install:
  - call .ci\deps.bat

build_script:
  - call .ci\build.bat

test_script:
  - call .ci\test.bat

after_test:
  - call .ci\package.bat

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: ffw-*.zip
    name: Compiled

#---------------------------------#
#           deployment            #
#---------------------------------#
deploy:
  description: 'Binary distribution of FineFramework'
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  auth_token:
    secure: Iy3zJbGrOW9X8aiAYoBX+xHl9mlapXwHrLlsHqrlKFGpXapjiv/lQVZZz3npjPTJ
  on:
    branch: master
    appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  - provider: Email
    to:
      - matusnov@gmail.com
